// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS5k29udIpFP02nuJAcPXYVd5WtDWCVeI',
    appId: '1:1057011839530:web:d1ba5e78770bb49e778953',
    messagingSenderId: '1057011839530',
    projectId: 'gymvisa-d2c4a',
    authDomain: 'gymvisa-d2c4a.firebaseapp.com',
    storageBucket: 'gymvisa-d2c4a.appspot.com',
    measurementId: 'G-GZF7QT1B2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvRkKHiXaxLiq4dgRESkH9KkLC_NnZ3M',
    appId: '1:1057011839530:android:7e11e7a5d679baad778953',
    messagingSenderId: '1057011839530',
    projectId: 'gymvisa-d2c4a',
    storageBucket: 'gymvisa-d2c4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeCyvPl7ItPQ5DF8yB0nvnyYDEkOEW4-A',
    appId: '1:1057011839530:ios:9320e2ce013531b1778953',
    messagingSenderId: '1057011839530',
    projectId: 'gymvisa-d2c4a',
    storageBucket: 'gymvisa-d2c4a.appspot.com',
    iosBundleId: 'com.example.gymvisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeCyvPl7ItPQ5DF8yB0nvnyYDEkOEW4-A',
    appId: '1:1057011839530:ios:26970059828abc39778953',
    messagingSenderId: '1057011839530',
    projectId: 'gymvisa-d2c4a',
    storageBucket: 'gymvisa-d2c4a.appspot.com',
    iosBundleId: 'com.example.gymvisa.RunnerTests',
  );
}
